version: "3.8"

services: 
   app:
      build: 
         context: .
         dockerfile: Dockerfile
      image: restapi     
      ports: 
         - 3000:3000
      volumes: 
         - .:/app
         - '/app/node_modules'
     


         
   mysql:
      image: mysql:8.0
      environment:
         - MYSQL_PASSWORD=tesla123
         - MYSQL_ROOT_PASSWORD=tesla123
         - MYSQL_DATABASE=productsdb
      ports:
         - 3366:3306
  
  

        
      

    